DROP DATABASE IF EXISTS `db_burbujas`;
CREATE DATABASE IF NOT EXISTS `db_burbujas`;
USE `db_burbujas`;  
 
CREATE TABLE clave_reset_tokens ( config_id BIGINT NOT NULL, expiry_date datetime  NOT NULL, id  BIGINT AUTO_INCREMENT NOT NULL, token VARCHAR(255)  NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE clientes ( eliminado BIT(1) NOT NULL, id  BIGINT AUTO_INCREMENT NOT NULL, direccion VARCHAR(255)  NULL, dni VARCHAR(255)  NULL, nombre_apellido VARCHAR(255)  NULL, telefono  VARCHAR(255)  NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE config ( entrega_pedidos_automatica BIT(1) NULL, timeout_alerta_rabastecimiento INT  NULL, id  BIGINT AUTO_INCREMENT NOT NULL, email_acceso  VARCHAR(50) NULL, clave_acceso  VARCHAR(60) NULL, nombre_lavanderia  VARCHAR(255)  NULL, logo_lavanderia BLOB NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE historial_estados_pedidos ( id  BIGINT AUTO_INCREMENT NOT NULL, fecha_hora_cambio_estado datetime  NOT NULL, pedido_id BIGINT NOT NULL, estado_anterior  VARCHAR(255)  NULL, estado_nuevo VARCHAR(255)  NOT NULL, eliminado TINYINT(1) DEFAULT 0  NOT NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE historial_maquinas_pedidos ( id BIGINT AUTO_INCREMENT NOT NULL, fecha_hora_asignacion datetime  NOT NULL, maquina_anterior_id BIGINT NULL, maquina_nueva_id  BIGINT NOT NULL, pedido_id BIGINT NOT NULL, eliminado TINYINT(1) DEFAULT 0  NOT NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE historial_productos_pedidos ( id BIGINT AUTO_INCREMENT NOT NULL, cantidad_producto DECIMAL(10, 2)  NOT NULL, fecha_hora_creacion datetime  NOT NULL, pedido_id BIGINT NOT NULL, producto_id BIGINT NOT NULL, eliminado TINYINT(1) DEFAULT 0  NOT NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE maquinas ( eliminado BIT(1) NOT NULL, numero  INT  NULL, id  BIGINT AUTO_INCREMENT NOT NULL, tipo  ENUM('NINGUNO','LAVADORA','SECADORA') NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE movimientos_caja ( id  BIGINT AUTO_INCREMENT NOT NULL, monto DECIMAL(10, 2)  NOT NULL, cliente_id BIGINT NULL, fecha datetime  NOT NULL, pedido_id  BIGINT NULL, proveedor_id BIGINT NULL, reabastecimiento_id  BIGINT NULL, descripcion  VARCHAR(255)  NULL, tipo_caja  VARCHAR(255)  NOT NULL, tipo_movimiento_caja ENUM('INGRESO','EGRESO','NOTACREDITO','NOTADEBITO')  NOT NULL, eliminado  TINYINT(1) DEFAULT 0  NOT NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE pedidos ( eliminado BIT(1) NOT NULL, precio DOUBLE NULL, cliente_id BIGINT NULL, fecha_hora_entrega datetime NULL, fecha_hora_ingreso datetime NULL, id BIGINT AUTO_INCREMENT NOT NULL, maquina_actual_id BIGINT NULL, tipo_id BIGINT NULL, descripcion VARCHAR(255) NULL, estado_actual ENUM('INGRESADO','PENDIENTE','LAVADO','SECADO','FINALIZADO','COBRADO','ENTREGADO','CANCELADO') NULL, prioridad ENUM('BAJA', 'NORMAL', 'PRIORITARIO', 'URGENTE') NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id));
CREATE TABLE productos ( cantidad_actual DOUBLE NULL, eliminado  BIT(1) NOT NULL, umbral_aviso_reabastecimiento DOUBLE NULL, id BIGINT AUTO_INCREMENT NOT NULL, tipo VARCHAR(255)  NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE proveedores ( eliminado BIT(1) NOT NULL, id  BIGINT AUTO_INCREMENT NOT NULL, cuit  VARCHAR(255)  NULL, direccion VARCHAR(255)  NULL, nombre  VARCHAR(255)  NULL, telefono  VARCHAR(255)  NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE reabastecimientos ( cantidad_producto DOUBLE NULL, eliminado BIT(1) NOT NULL, precio  DOUBLE NULL, fecha datetime  NULL, id BIGINT AUTO_INCREMENT NOT NULL, producto_id BIGINT NULL, proveedor_id  BIGINT NULL, tipo_caja ENUM('EFECTIVO','BANCO') NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE tipo_pedido_producto_mapping ( id BIGINT AUTO_INCREMENT NOT NULL, cantidad_usada DECIMAL(10, 2)  NOT NULL, producto_id  BIGINT NOT NULL, tipo_pedido_id BIGINT NOT NULL, eliminado  TINYINT(1) DEFAULT 0  NOT NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );
CREATE TABLE tipos_pedido ( eliminado BIT(1) NOT NULL, minutos_duracion_lavado INT  NULL, minutos_duracion_secado INT  NULL, id BIGINT AUTO_INCREMENT NOT NULL, descripcion VARCHAR(255)  NULL, CONSTRAINT `PRIMARY` PRIMARY KEY (id) );

ALTER TABLE clave_reset_tokens ADD CONSTRAINT UK_42lb6i0ekc7qgqatdr957w24f UNIQUE (config_id);
ALTER TABLE clave_reset_tokens ADD CONSTRAINT FK9ftiwbgwkvjqq5w6ekl7btafr FOREIGN KEY (config_id) REFERENCES config (id) ON DELETE NO ACTION;
ALTER TABLE pedidos ADD CONSTRAINT FKdtij5xqjiq3cmee35fmqixps8 FOREIGN KEY (maquina_actual_id) REFERENCES maquinas (id) ON DELETE NO ACTION;
CREATE INDEX FKdtij5xqjiq3cmee35fmqixps8 ON pedidos (maquina_actual_id);
ALTER TABLE reabastecimientos ADD CONSTRAINT FKf7kk7cqbsilolvjtx4btnjy2w FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE NO ACTION;
CREATE INDEX FKf7kk7cqbsilolvjtx4btnjy2w ON reabastecimientos (producto_id);
ALTER TABLE pedidos ADD CONSTRAINT FKg7202lk0hwxn04bmdl2thth5b FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE NO ACTION;
CREATE INDEX FKg7202lk0hwxn04bmdl2thth5b ON pedidos (cliente_id);
ALTER TABLE pedidos ADD CONSTRAINT FKmlqdbxu6t1t37k4hdwjhdjipi FOREIGN KEY (tipo_id) REFERENCES tipos_pedido (id) ON DELETE NO ACTION;
CREATE INDEX FKmlqdbxu6t1t37k4hdwjhdjipi ON pedidos (tipo_id);
ALTER TABLE reabastecimientos ADD CONSTRAINT FKsrx94k0r0fpn5onbttjfp3rc2 FOREIGN KEY (proveedor_id) REFERENCES proveedores (id) ON DELETE NO ACTION;
CREATE INDEX FKsrx94k0r0fpn5onbttjfp3rc2 ON reabastecimientos (proveedor_id);
ALTER TABLE historial_estados_pedidos ADD CONSTRAINT historial_estados_pedidos_ibfk_1 FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE NO ACTION;
ALTER TABLE historial_maquinas_pedidos ADD CONSTRAINT historial_maquinas_pedidos_ibfk_1 FOREIGN KEY (maquina_anterior_id) REFERENCES maquinas (id) ON DELETE NO ACTION;
CREATE INDEX maquina_anterior_id ON historial_maquinas_pedidos (maquina_anterior_id);
ALTER TABLE historial_maquinas_pedidos ADD CONSTRAINT historial_maquinas_pedidos_ibfk_2 FOREIGN KEY (maquina_nueva_id) REFERENCES maquinas (id) ON DELETE NO ACTION;
CREATE INDEX maquina_nueva_id ON historial_maquinas_pedidos (maquina_nueva_id);
ALTER TABLE historial_maquinas_pedidos ADD CONSTRAINT historial_maquinas_pedidos_ibfk_3 FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE NO ACTION;
ALTER TABLE historial_productos_pedidos ADD CONSTRAINT historial_productos_pedidos_ibfk_1 FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE NO ACTION;
CREATE INDEX pedido_id ON movimientos_caja (pedido_id);
ALTER TABLE historial_productos_pedidos ADD CONSTRAINT historial_productos_pedidos_ibfk_2 FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE NO ACTION;
CREATE INDEX producto_id ON tipo_pedido_producto_mapping (producto_id);
CREATE INDEX tipo_pedido_id ON tipo_pedido_producto_mapping (tipo_pedido_id);
ALTER TABLE movimientos_caja ADD CONSTRAINT movimientos_caja_ibfk_1 FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE NO ACTION;
CREATE INDEX cliente_id ON movimientos_caja (cliente_id);
ALTER TABLE movimientos_caja ADD CONSTRAINT movimientos_caja_ibfk_2 FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE NO ACTION;
ALTER TABLE movimientos_caja ADD CONSTRAINT movimientos_caja_ibfk_3 FOREIGN KEY (proveedor_id) REFERENCES proveedores (id) ON DELETE NO ACTION;
CREATE INDEX proveedor_id ON movimientos_caja (proveedor_id);
ALTER TABLE movimientos_caja ADD CONSTRAINT movimientos_caja_ibfk_4 FOREIGN KEY (reabastecimiento_id) REFERENCES reabastecimientos (id) ON DELETE NO ACTION;
CREATE INDEX reabastecimiento_id ON movimientos_caja (reabastecimiento_id);
ALTER TABLE tipo_pedido_producto_mapping ADD CONSTRAINT tipo_pedido_producto_mapping_ibfk_1 FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE NO ACTION;
ALTER TABLE tipo_pedido_producto_mapping ADD CONSTRAINT tipo_pedido_producto_mapping_ibfk_2 FOREIGN KEY (tipo_pedido_id) REFERENCES tipos_pedido (id) ON DELETE NO ACTION;