
services:
  gestion-limpia:
    build:
      context: .
    image: hernanfrank/gestion-limpia:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: db_burbujas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: