services:
  gestion-limpia:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file: ".env"
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy
  mysql_db:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    networks:
      - app-network
    env_file: ".env"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
networks:
  app-network:
    driver: bridge