FROM eclipse-temurin:17-jdk-jammy

# Parámetro opcional para el archivo JAR, por defecto apunta al "target" estándar
ARG JAR_FILE=target/gestion-limpia-1.0.jar

# Copiar el archivo JAR al contenedor
COPY ${JAR_FILE} app.jar

# Exponer el puerto en el que la aplicación escucha
EXPOSE 8080

# Usar las variables de entorno para sobrescribir configuraciones sensibles
# Asegúrate de que las variables del archivo .env estén disponibles
ENTRYPOINT ["java", "-Dspring.config.location=classpath:/application.properties", "-jar", "/app.jar"]